/**
 * FreeGPT4-Web-API Provider
 *
 * Implements IAIProvider for a self-hosted FreeGPT4 web API (e.g. Free-GPT4-WEB-API)
 */

import { getLogger } from "./logger";
import {
  IAIProvider,
  AIProviderType,
  AICompletionOptions,
  AIExplanationOptions,
  AIRefactoringOptions,
  AICommitOptions,
  AIResult,
} from "./aiProvider";

const logger = getLogger("FreeGPTProvider");

export class FreeGPTProvider implements IAIProvider {
  readonly type: AIProviderType = "local";
  private baseUrl: string;
  private ready = false;

  private constructor(baseUrl: string, ready = false) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.ready = ready;
  }

  /**
   * Factory that probes the server and returns a ready provider when reachable
   */
  static async create(baseUrl = "http://127.0.0.1:5500/"): Promise<FreeGPTProvider> {
    const provider = new FreeGPTProvider(baseUrl, false);

    try {
      const probe = await provider.callAPI("ping", 10);
      if (probe && probe.length > 0) {
        provider.ready = true;
        logger.info("FreeGPT provider reachable", { baseUrl });
      } else {
        logger.warn("FreeGPT probe returned empty response", { baseUrl });
      }
    } catch (err) {
      logger.warn("FreeGPT provider probe failed", { error: String(err), baseUrl });
    }

    return provider;
  }

  get isAvailable(): boolean {
    return this.ready;
  }

  isReady(): boolean {
    return this.ready;
  }

  async getCompletion(options: AICompletionOptions): Promise<AIResult | null> {
    if (!this.isReady()) {
      return null;
    }

    const prompt = `You are a helpful coding assistant for ${options.language}.\n\n${options.prompt}`;
    try {
      const text = await this.callAPI(prompt, options.maxTokens || 200);
      return {
        text: text || "",
        reasoning: "Generated by FreeGPT local server",
        confidence: 0.6,
      };
    } catch (error) {
      logger.error("FreeGPT completion failed", { error: String(error) });
      return null;
    }
  }

  async getExplanation(options: AIExplanationOptions): Promise<string | null> {
    if (!this.isReady()) {
      return null;
    }

    const typePrompt = {
      why: "Explain WHY this code pattern is used (its purpose and benefits)",
      how: "Explain HOW this code works step by step",
      what: "Explain WHAT this code does in simple terms",
    }[options.type || "what"];

    const prompt = `${typePrompt}\n\n${options.code}`;

    try {
      const text = await this.callAPI(prompt, 150);
      return text || null;
    } catch (error) {
      logger.error("FreeGPT explanation failed", { error: String(error) });
      return null;
    }
  }

  async getRefactoringSuggestions(options: AIRefactoringOptions): Promise<AIResult | null> {
    if (!this.isReady()) {
      return null;
    }

    const categoryDesc = {
      readability: "improve readability and clarity",
      performance: "improve performance and efficiency",
      maintainability: "improve maintainability and structure",
      security: "improve security and safety",
    }[options.category || "readability"];

    const prompt = `Suggest one key refactoring to ${categoryDesc}:\n\n${options.code}`;

    try {
      const text = await this.callAPI(prompt, 300);
      return {
        text: text || "",
        reasoning: "Refactoring suggestion from FreeGPT",
        confidence: 0.6,
      };
    } catch (error) {
      logger.error("FreeGPT refactor failed", { error: String(error) });
      return null;
    }
  }

  async generateCommitMessage(options: AICommitOptions): Promise<string | null> {
    if (!this.isReady()) {
      return null;
    }

    const prompt = `Generate a conventional commit message for these changes. Files: ${options.files?.join(", ") || "various"}\n\nDiff:\n${options.diff}`;
    try {
      const text = await this.callAPI(prompt, 100);
      return text ? text.trim() : null;
    } catch (error) {
      logger.error("FreeGPT commit message failed", { error: String(error) });
      return null;
    }
  }

  async generateQuickCommit(options: AICommitOptions): Promise<string | null> {
    if (!this.isReady()) {
      return null;
    }
    const prompt = `Generate a SHORT commit subject (<50 chars) for these changes:\n${options.diff.slice(0, 500)}`;
    try {
      const text = await this.callAPI(prompt, 40);
      return text ? text.trim() : null;
    } catch (error) {
      logger.error("FreeGPT quick commit failed", { error: String(error) });
      return null;
    }
  }

  /**
   * Call the FreeGPT web API. Tries a GET with `text` query parameter and falls back to POST JSON.
   */
  private async callAPI(prompt: string, maxTokens = 200): Promise<string> {
    const url = `${this.baseUrl}/`;

    // Try GET first (many Free-GPT4 servers accept ?text=...)
    try {
      const q = new URL(url);
      q.searchParams.set("text", prompt);
      q.searchParams.set("max_tokens", String(maxTokens));

      const res = await fetch(q.toString(), {
        method: "GET",
        headers: { Accept: "text/plain, */*" },
      });

      if (res.ok) {
        const txt = await res.text();
        return txt;
      }
      // otherwise fall through to POST attempt
    } catch (err) {
      logger.debug("FreeGPT GET attempt failed, will try POST", { error: String(err) });
    }

    // POST JSON fallback
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "text/plain, */*" },
        body: JSON.stringify({ text: prompt, max_tokens: maxTokens }),
      });

      if (!res.ok) {
        throw new Error(`HTTP ${res.status}`);
      }

      return await res.text();
    } catch (error) {
      throw new Error(`FreeGPT API call failed: ${String(error)}`);
    }
  }
}

export default FreeGPTProvider;
